parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     bb_cdz
    database_user:     bbdemo
    database_password: demodemo

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            es
    secret:            asjdfjaskdfjladsjfkaldjiuaiodfuoi288